### ISSUE TITLE
[B] First run shading menu gives error last_mode

### ISSUE THREAD

**Issue by schroef** [Exairnous/Advanced-UI-Menus#4]
I noticed when we first run the shading menu it gives this error for last_mode. I think adding a check at startup will solve this. Not every users start in the same shading mode, so hardcoding this wont be an option.

![screen shot 2018-05-12 at 6 05 11 pm](https://user-images.githubusercontent.com/6923008/39961935-4317d7d8-560f-11e8-94a7-f26bb72960b1.png)

**Comment by Exairnous** [comment]
I see, I have an idea, and will get back to you later

**Comment by schroef** [comment]
I changed line 38 and dont see the error. Not sure it solves it properly though. The modal menu's are a bit weird to work with. I still havent figured out how long i need to press the key.

![screen shot 2018-05-12 at 6 14 53 pm](https://user-images.githubusercontent.com/6923008/39961982-6b58ba36-5610-11e8-996f-4d045ec2ce3b.png)

**Comment by Exairnous** [comment]
0.3 seconds. 

I think I have a fix for this, but I don't have time right now.  I'll get back to you :)

**Comment by schroef** [comment]
okay, no worries... its not life-threatening ;)

**Comment by Exairnous** [comment]
Ok, the fix for this is very simple :)
All I have to do is replace this:

    last_mode = ['WIREFRAME']

with this:

    last_mode = ['WIREFRAME', 'SOLID']

I'll commit that after the preferences are sorted out.

**Comment by Exairnous** [comment]
Fixed and committed to the development branch.
