### ISSUE TITLE
[B]Could not get delete menu to popup

### ISSUE THREAD

**Issue by schroef** [Exairnous/Advanced-UI-Menus#7]
Yesterday i ran into an issue with the delete menu. I did not study the all if very properly but in edit mode i would just not show. First i thought it perhaps not getting the first call properly so i tried in object mode and then in edit mode. Still nothing was showing. 

Below is a screengrab of the error i saw in the console.

<img width="817" alt="screen shot 2018-08-25 at 20 27 56" src="https://user-images.githubusercontent.com/6923008/44829737-36833480-abec-11e8-92a2-d043c908bba3.png">

Not sure why the mode shows up though? Not even sure how that is related. I was busy and didnt want to forget about it so i made a quick screengrab and eventually deleted it by using the mesh menu.

**Comment by Exairnous** [comment]
Can you walk me through what you were doing when the error popped up?  What objects you were working with and their types, etc.?  Also, if you know how I could replicate it that would be great!

**Comment by schroef** [comment]
Thats the problem, i tried replicating it and could not get it to show. I do remember seeing the issue before. Somehow i thought it was something when working with a armature and deleting stuff. I did try that but could get it to show.

Ill try it again later or when it happens look what happened before that.

**Comment by Exairnous** [comment]
If you find anything that'll be great.  I'll keep my eyes open and if it happens to me I'll see what I can do.

**Comment by schroef** [comment]
Okay i found another example finally. Here's the screengrab of the error. It happens when i open  the model which was already in edge mode. I wanted to dissolve edges.

<img width="1066" alt="delete menu not showing" src="https://user-images.githubusercontent.com/6923008/45937241-51975900-bf8c-11e8-8483-99cab65a9534.png">

**Comment by Exairnous** [comment]
Thanks!  This helps a lot.  It's a real weird bug, but I should hopefully be able to fix it.

**Comment by schroef** [comment]
I still don't understand why it pops up now and than. This specific scene showed it time I opened it and closed it. Didn't adjust anything and was checking why it happened.

Holy you understand it. Seems something which makes the list or history statement

**Comment by schroef** [comment]
I found a new model which has the same issue. This time i also separated it into its own file. I tried this before but than suddenly the menu started working and i didnt understand why.

I noticed this code in the console. But is same as the last time i believe.

```
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/Advanced_UI_Menus/delete_menu.py", line 34, in draw
    selected = self.init()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/Advanced_UI_Menus/delete_menu.py", line 16, in init
    sel_verts_num, sel_edges_num, sel_faces_num = get_selected()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/Advanced_UI_Menus/Utils/core.py", line 69, in get_selected
    sel_verts_num = (e for e in bpy.context.scene.statistics().split(" | ")
StopIteration

location: <unknown location>:-1

location: <unknown location>:-1
```
[No delete menu.blend.zip](https://github.com/Exairnous/Advanced-UI-Menus/files/2516214/No.delete.menu.blend.zip)

I went on add looked at that code. It seems it does have some data. Not sure what causes this stop. This is what i got printed before that error shows.

```
## Sel vets : v2.79 | (Key) Verts:3,392/3,392 | Edges:6,720/6,720 | Faces:3,328/3,328 | Tris:6,656 | Mem:20.86M | Thunderstick_Applied
```

When i noticed the word (key), i know whats causing it. Its shapeskeys!!!

When we have a shape key on a model, than the delete menu doesnt work. Perhaps because of the word between parenthesis??

See screengrab of shapekeys vs no shapekeys
![shapekeys vs no shapekeys](https://www.dropbox.com/s/m2tgfyfl63ml3of/shapekeys-vs-no-shapekeys.gif?raw=1)

**Comment by schroef** [comment]
This quick test will fix it... but why not call this action one time. I see you can those statics a couple times? Isnt it better to call it once and than use that list for the other items?

```
sel_verts_num = (e for e in bpy.context.scene.statistics().split(" | ")
                                    if e.startswith("(Key) Verts:")
                                    or e.startswith("Verts:")).__next__().split("/")

                                  #if e.startswith("Verts:")).__next__()[6:].split("/")
    # turn the number of verts from a string to an int
    sel_verts_num = int(sel_verts_num[1].replace(",",""))
    
```
I took out the [6:] and then in the int check used the second in the list. It does work when there is a shape key or not.

**Comment by Exairnous** [comment]
Fixed and committed to the development branch.

Thanks for getting to the bottom of this!  I had no idea shapekeys did that.  I have refactored the get_selected function fix the error, and hopefully, be simpler and more robust.


    def get_selected():
        # get a list of statistics from the info bar
        stats = bpy.context.scene.statistics().split(" | ")

        # get number of selected verts
        sel_verts = int(stats[1].split(":")[1].split("/")[0])
    
        # get number of selected edges
        sel_edges = int(stats[2].split(":")[1].split("/")[0])
    
        # get number of selected faces
        sel_faces = int(stats[3].split(":")[1].split("/")[0])
    
        return sel_verts, sel_edges, sel_faces
