### ISSUE TITLE
[B]Subdive mesh above 1 collapses mesh

### ISSUE THREAD

**Issue by schroef** [Exairnous/Advanced-UI-Menus#8]
v 1.5b
bl 2.79b
os 10.11.6

I know this sounds weird, and i have noticed before. But when i add an object and use subdivide in edit mode, from dive 2 and up the complete mesh collapses. It happens with all meshes and also in both Blender versions i have (2.79b, 2.78c). When deactivating the addon the subdivide menu does work and mesh keeps its form.

Looking in the console i dont see any error report or what so ever. I dont understand why it would mess with mesh, because that doesnt make any sense to me

See attached screengrab
![subdivide-causes-mesh-collapse](https://user-images.githubusercontent.com/6923008/44868237-45073580-ac58-11e8-9782-365858ec045c.gif)

It does work when i add first one subdivision, go to object mode, go back into edit mode and than do more subdivisions.

See screengrab 2
![subdivide-causes-no-collapse](https://user-images.githubusercontent.com/6923008/44868256-54867e80-ac58-11e8-8ccb-8c355e587d57.gif)

PS current version doesnt remove the hotkeys. That is the test version i got, i think i need to check that part

**Comment by Exairnous** [comment]
I have no idea why it's doing that.  I have noticed this phenomenon for a while now, but didn't know my addon was causing it.  I'll keep it in mind, but I don't think this is going to be an easy fix.

About the hotkeys, my addon doesn't remove hotkeys anymore it overrides them.  This works for me and so far I haven't heard differently, unless this is you telling me that it doesn't work for you?  Or do you mean it's not removing its hotkeys when deactivated?

**Comment by schroef** [comment]
Im not sure what the unkown operator error is, i actually see it on more addons. Also on another im doing. But also hardops does it. I even checked the devoper site and saw something about a new daily build which fixes this missing unknow operator error. Its not really something big, but i didnt understand why it was showing. I mean all the operators where gone, its something done by keymaps i guess.

I do noticed one issue when i manually removed all the double shortcuts i somehow got from Advanced menus, now many basic ones didnt work. All those which are replaced by Advanced menus didnt work. That could be an issue i guess. Perhaps i removed to much though, lol.

That collapsing is super weird indeed, no code is put out and and only happens if you do it on a mesh the first time. Say you subdivide it once, then go to object mode and back into edit mode and redo it but this time with more. Than it works just fine.

Could it be connected somehow to some kind of history state you are recording? Just thinking out loud here.

**Comment by Exairnous** [comment]
I don't think it's a history thing, I don't store anything that should affect a mesh, but I'll look into this and see if I can pinpoint what's causing it.

Double shortcuts?  I've never heard of that.  I just tested and manually removing seems to work fine for me, the blender defaults seem to work fine as well as the Pie Menus Official.  Probably something weird on your end, but let me know if the issue persists.

Yeah, the unknown operator error is a weird one.  If you come across how to fix it let me know.  Maybe it's because I do register module and don't register each operator individually?

**Comment by Exairnous** [comment]
Fixed and committed to the development branch.

The problem ended up being with the EditorModeOperator in mode_menu.py.  I guess when it was called it left the undo stack in a weird state, so when you changed the subdivisions it collapsed the mesh.  To fix it all I had to do was add 'UNDO' to bl_options in the EditorModeOperator.
